version: 2

project_name: spacewalk

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: spacewalk
    main: ./cmd/spacewalk
    binary: spacewalk
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: spacewalk
    ids:
      - spacewalk
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: sharmasuraj0123
    name: space-walk
